#!/bin/sh
RETVAL=0

start() {
        echo starting
	      echo `RAILS_ENV=production puma -p 3001 >/dev/null 2>&1` &
}

stop() {
        echo `ps aux | grep puma | grep -v grep | awk -F " "  '{ print $2}' | xargs kill`
}

update() {
        echo pulling from github
        git pull origin master
        echo installing gems
        bundle install
        echo migrating db
        RAILS_ENV=production bundle exec rake db:migrate
        echo bundle exec rake assets:precompile
        RAILS_ENV=production bundle exec rake assets:clean assets:precompile
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   update)
      update
      stop
      start
      ;;
   justupdate)
      update
      ;;
   *)
      echo $"Usage: trame { start | stop | restart | update | justupdate }"
      RETVAL=3
esac

exit $RETVAL
